version: '3.1'

services:
  
  mysql-db:
    image: mysql:latest
    ports:
        - 3306:3306
    environment:
      MYSQL_DATABASE: just-learn
      
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
